from __future__ import annotations

UI_FAMILY = "Segoe UI"
EMOJI_FAMILY = "Segoe UI Emoji"
SYMBOL_FAMILY = "Segoe UI Symbol"
MDL2_FAMILY = "Segoe MDL2 Assets"
MONO_FAMILY = "Consolas"

FONT_UI = (UI_FAMILY, 9)
FONT_UI_STRONG = (UI_FAMILY, 9, "bold")
FONT_UI_SMALL = (UI_FAMILY, 8)
FONT_UI_TINY = (UI_FAMILY, 7)
FONT_CONTROL = (UI_FAMILY, 9)
FONT_CONTROL_STRONG = (UI_FAMILY, 9, "bold")
FONT_WINDOW_TITLE = (UI_FAMILY, 14, "bold")
FONT_SECTION_TITLE = (UI_FAMILY, 11, "bold")
FONT_CARD_TITLE = (UI_FAMILY, 10)
FONT_CARD_TITLE_STRONG = (UI_FAMILY, 10, "bold")
FONT_PREVIEW_TITLE = (UI_FAMILY, 11, "bold")
FONT_PREVIEW_LABEL = (UI_FAMILY, 9, "bold")
FONT_PLUGIN_ICON = (EMOJI_FAMILY, 20)
FONT_PLUGIN_ICON_SMALL = (EMOJI_FAMILY, 18)
