// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_extract_sub_pedigree_cpp
LogicalVector fast_extract_sub_pedigree_cpp(CharacterVector ids, CharacterVector sires, CharacterVector dams, CharacterVector target_ids, int max_depth, CharacterVector missing);
RcppExport SEXP _pedigreekit_fast_extract_sub_pedigree_cpp(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP target_idsSEXP, SEXP max_depthSEXP, SEXP missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target_ids(target_idsSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type missing(missingSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_extract_sub_pedigree_cpp(ids, sires, dams, target_ids, max_depth, missing));
    return rcpp_result_gen;
END_RCPP
}
// fast_pedigree_qc
List fast_pedigree_qc(CharacterVector ids, CharacterVector sires, CharacterVector dams);
RcppExport SEXP _pedigreekit_fast_pedigree_qc(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_pedigree_qc(ids, sires, dams));
    return rcpp_result_gen;
END_RCPP
}
// fast_pedigree_qc_sex
List fast_pedigree_qc_sex(CharacterVector ids, CharacterVector sires, CharacterVector dams, CharacterVector sex);
RcppExport SEXP _pedigreekit_fast_pedigree_qc_sex(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP sexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sex(sexSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_pedigree_qc_sex(ids, sires, dams, sex));
    return rcpp_result_gen;
END_RCPP
}
// fast_detect_loops
List fast_detect_loops(CharacterVector ids, CharacterVector sires, CharacterVector dams);
RcppExport SEXP _pedigreekit_fast_detect_loops(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_detect_loops(ids, sires, dams));
    return rcpp_result_gen;
END_RCPP
}
// fast_find_deepest_ancestor
List fast_find_deepest_ancestor(CharacterVector ids, CharacterVector sires, CharacterVector dams, int sample_size);
RcppExport SEXP _pedigreekit_fast_find_deepest_ancestor(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_find_deepest_ancestor(ids, sires, dams, sample_size));
    return rcpp_result_gen;
END_RCPP
}
// check_birth_date_order
List check_birth_date_order(CharacterVector ids, CharacterVector sires, CharacterVector dams, NumericVector birth_dates);
RcppExport SEXP _pedigreekit_check_birth_date_order(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP birth_datesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type birth_dates(birth_datesSEXP);
    rcpp_result_gen = Rcpp::wrap(check_birth_date_order(ids, sires, dams, birth_dates));
    return rcpp_result_gen;
END_RCPP
}
// fast_lap_distribution
NumericVector fast_lap_distribution(CharacterVector ids, CharacterVector sires, CharacterVector dams, int sample_size, int max_depth);
RcppExport SEXP _pedigreekit_fast_lap_distribution(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP sample_sizeSEXP, SEXP max_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lap_distribution(ids, sires, dams, sample_size, max_depth));
    return rcpp_result_gen;
END_RCPP
}
// fast_lap_depths
IntegerVector fast_lap_depths(CharacterVector ids, CharacterVector sires, CharacterVector dams);
RcppExport SEXP _pedigreekit_fast_lap_depths(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lap_depths(ids, sires, dams));
    return rcpp_result_gen;
END_RCPP
}
// fast_descendant_summary
List fast_descendant_summary(CharacterVector ids, CharacterVector parent_vals, int max_depth);
RcppExport SEXP _pedigreekit_fast_descendant_summary(SEXP idsSEXP, SEXP parent_valsSEXP, SEXP max_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type parent_vals(parent_valsSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_descendant_summary(ids, parent_vals, max_depth));
    return rcpp_result_gen;
END_RCPP
}
// fast_inbreeding_cpp
NumericVector fast_inbreeding_cpp(CharacterVector ids, CharacterVector sires, CharacterVector dams);
RcppExport SEXP _pedigreekit_fast_inbreeding_cpp(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_inbreeding_cpp(ids, sires, dams));
    return rcpp_result_gen;
END_RCPP
}
// fast_ancestor_contribution_triplet_cpp
Rcpp::List fast_ancestor_contribution_triplet_cpp(Rcpp::CharacterVector ids, Rcpp::CharacterVector sires, Rcpp::CharacterVector dams, Rcpp::NumericVector F, Rcpp::IntegerVector target_indices, int top_k, int max_depth, bool return_ratio);
RcppExport SEXP _pedigreekit_fast_ancestor_contribution_triplet_cpp(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP FSEXP, SEXP target_indicesSEXP, SEXP top_kSEXP, SEXP max_depthSEXP, SEXP return_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type F(FSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type target_indices(target_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type return_ratio(return_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ancestor_contribution_triplet_cpp(ids, sires, dams, F, target_indices, top_k, max_depth, return_ratio));
    return rcpp_result_gen;
END_RCPP
}
// fast_top_contrib_cpp
Rcpp::DataFrame fast_top_contrib_cpp(Rcpp::CharacterVector ids, Rcpp::CharacterVector sires, Rcpp::CharacterVector dams, Rcpp::NumericVector F, std::string target_id, int max_depth, int top_k);
RcppExport SEXP _pedigreekit_fast_top_contrib_cpp(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP FSEXP, SEXP target_idSEXP, SEXP max_depthSEXP, SEXP top_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type F(FSEXP);
    Rcpp::traits::input_parameter< std::string >::type target_id(target_idSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_top_contrib_cpp(ids, sires, dams, F, target_id, max_depth, top_k));
    return rcpp_result_gen;
END_RCPP
}
// fast_ancestor_contribution_bulk_cpp
Rcpp::DataFrame fast_ancestor_contribution_bulk_cpp(Rcpp::CharacterVector ids, Rcpp::CharacterVector sires, Rcpp::CharacterVector dams, Rcpp::NumericVector F, int top_k, int max_depth, bool return_ratio);
RcppExport SEXP _pedigreekit_fast_ancestor_contribution_bulk_cpp(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP FSEXP, SEXP top_kSEXP, SEXP max_depthSEXP, SEXP return_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type F(FSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type return_ratio(return_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ancestor_contribution_bulk_cpp(ids, sires, dams, F, top_k, max_depth, return_ratio));
    return rcpp_result_gen;
END_RCPP
}
// fast_fix_pedigree_cpp
Rcpp::List fast_fix_pedigree_cpp(Rcpp::CharacterVector progeny, Rcpp::CharacterVector sires, Rcpp::CharacterVector dams, Rcpp::Nullable<Rcpp::CharacterVector> sex, Rcpp::Nullable<Rcpp::NumericVector> birthdate, Rcpp::CharacterVector missing);
RcppExport SEXP _pedigreekit_fast_fix_pedigree_cpp(SEXP progenySEXP, SEXP siresSEXP, SEXP damsSEXP, SEXP sexSEXP, SEXP birthdateSEXP, SEXP missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type progeny(progenySEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type dams(damsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type birthdate(birthdateSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type missing(missingSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fix_pedigree_cpp(progeny, sires, dams, sex, birthdate, missing));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pedigreekit_fast_extract_sub_pedigree_cpp", (DL_FUNC) &_pedigreekit_fast_extract_sub_pedigree_cpp, 6},
    {"_pedigreekit_fast_pedigree_qc", (DL_FUNC) &_pedigreekit_fast_pedigree_qc, 3},
    {"_pedigreekit_fast_pedigree_qc_sex", (DL_FUNC) &_pedigreekit_fast_pedigree_qc_sex, 4},
    {"_pedigreekit_fast_detect_loops", (DL_FUNC) &_pedigreekit_fast_detect_loops, 3},
    {"_pedigreekit_fast_find_deepest_ancestor", (DL_FUNC) &_pedigreekit_fast_find_deepest_ancestor, 4},
    {"_pedigreekit_check_birth_date_order", (DL_FUNC) &_pedigreekit_check_birth_date_order, 4},
    {"_pedigreekit_fast_lap_distribution", (DL_FUNC) &_pedigreekit_fast_lap_distribution, 5},
    {"_pedigreekit_fast_lap_depths", (DL_FUNC) &_pedigreekit_fast_lap_depths, 3},
    {"_pedigreekit_fast_descendant_summary", (DL_FUNC) &_pedigreekit_fast_descendant_summary, 3},
    {"_pedigreekit_fast_inbreeding_cpp", (DL_FUNC) &_pedigreekit_fast_inbreeding_cpp, 3},
    {"_pedigreekit_fast_ancestor_contribution_triplet_cpp", (DL_FUNC) &_pedigreekit_fast_ancestor_contribution_triplet_cpp, 8},
    {"_pedigreekit_fast_top_contrib_cpp", (DL_FUNC) &_pedigreekit_fast_top_contrib_cpp, 7},
    {"_pedigreekit_fast_ancestor_contribution_bulk_cpp", (DL_FUNC) &_pedigreekit_fast_ancestor_contribution_bulk_cpp, 7},
    {"_pedigreekit_fast_fix_pedigree_cpp", (DL_FUNC) &_pedigreekit_fast_fix_pedigree_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_pedigreekit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
