# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_extract_sub_pedigree_cpp <- function(ids, sires, dams, target_ids, max_depth, missing) {
    .Call(`_pedigreekit_fast_extract_sub_pedigree_cpp`, ids, sires, dams, target_ids, max_depth, missing)
}

fast_pedigree_qc <- function(ids, sires, dams) {
    .Call(`_pedigreekit_fast_pedigree_qc`, ids, sires, dams)
}

fast_pedigree_qc_sex <- function(ids, sires, dams, sex) {
    .Call(`_pedigreekit_fast_pedigree_qc_sex`, ids, sires, dams, sex)
}

fast_detect_loops <- function(ids, sires, dams) {
    .Call(`_pedigreekit_fast_detect_loops`, ids, sires, dams)
}

fast_find_deepest_ancestor <- function(ids, sires, dams, sample_size = 200L) {
    .Call(`_pedigreekit_fast_find_deepest_ancestor`, ids, sires, dams, sample_size)
}

check_birth_date_order <- function(ids, sires, dams, birth_dates) {
    .Call(`_pedigreekit_check_birth_date_order`, ids, sires, dams, birth_dates)
}

fast_lap_distribution <- function(ids, sires, dams, sample_size = 10000L, max_depth = 20L) {
    .Call(`_pedigreekit_fast_lap_distribution`, ids, sires, dams, sample_size, max_depth)
}

fast_lap_depths <- function(ids, sires, dams) {
    .Call(`_pedigreekit_fast_lap_depths`, ids, sires, dams)
}

fast_descendant_summary <- function(ids, parent_vals, max_depth = 50L) {
    .Call(`_pedigreekit_fast_descendant_summary`, ids, parent_vals, max_depth)
}

fast_inbreeding_cpp <- function(ids, sires, dams) {
    .Call(`_pedigreekit_fast_inbreeding_cpp`, ids, sires, dams)
}

fast_ancestor_contribution_triplet_cpp <- function(ids, sires, dams, F, target_indices, top_k = 5L, max_depth = 6L, return_ratio = TRUE) {
    .Call(`_pedigreekit_fast_ancestor_contribution_triplet_cpp`, ids, sires, dams, F, target_indices, top_k, max_depth, return_ratio)
}

fast_top_contrib_cpp <- function(ids, sires, dams, F, target_id, max_depth = 6L, top_k = 5L) {
    .Call(`_pedigreekit_fast_top_contrib_cpp`, ids, sires, dams, F, target_id, max_depth, top_k)
}

fast_ancestor_contribution_bulk_cpp <- function(ids, sires, dams, F, top_k = 5L, max_depth = 6L, return_ratio = TRUE) {
    .Call(`_pedigreekit_fast_ancestor_contribution_bulk_cpp`, ids, sires, dams, F, top_k, max_depth, return_ratio)
}

fast_fix_pedigree_cpp <- function(progeny, sires, dams, sex = NULL, birthdate = NULL, missing = as.character( c("0", "na", "NA", "", " "))) {
    .Call(`_pedigreekit_fast_fix_pedigree_cpp`, progeny, sires, dams, sex, birthdate, missing)
}

